spring:
  datasource:
    url: jdbc:sqlite:/Users/mac/.alist_data/data.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    web: DEBUG