server:
  port: 5245
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    open-in-view: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  devtools:
    add-properties: false

