POST http://localhost/api/v1/alist/setting
Content-Type: application/json

{
}

###
POST http://localhost:5245/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
