###

POST http://localhost/api/v1/open/initialize
Content-Type: application/json

{
  "password": "888888"
}


###

POST http://localhost:5245/api/v1/search_node/build
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNzA2NjA3MTY0LCJuYmYiOjE3MDY0MzQzNjQsImlhdCI6MTcwNjQzNDM2NH0.4vlyUizUcXYCcYKf21Qxr8qq-n4JbWawm35KNlEDBHs

{}
